### ISSUE TITLE
Mapbox如何给glb模型增加阴影效果

### ISSUE THREAD

**Issue by Zhupengcheng26** [mapbox-developer-group/Mapbox-Tech-Q-A#31]

**Comment by Jing-flyloveyin** [comment]
@Zhupengcheng26 请详细描述你的问题哦

**Comment by Zhupengcheng26** [comment]
我希望在mapbox所提供的地图上加载三维模型，mapbox支持glb格式模型的添加，但根据three.js的开发文档，我是可以给模型增加directionalLight或spotLight来给模型生成阴影，但这个效果在mapbox里实现不了，请问我该怎么做？
