### ISSUE TITLE
threebox

### ISSUE THREAD

**Issue by wuxiang1228** [mapbox-developer-group/Mapbox-Tech-Q-A#35]
![image](https://user-images.githubusercontent.com/40557858/71395633-b0e18e80-2651-11ea-9220-84d3e16c6ff6.png)
这个效果有案例么

**Comment by Jing-flyloveyin** [comment]
@wuxiang1228 图片可能不太清楚啊，另外标题请修改一下，太笼统啦，我先关了，您修改好把它打开就行
