### ISSUE TITLE
 mapbox gl  对栅格base64加密的瓦片  如何去解密

### ISSUE THREAD

**Issue by SCLGIS** [mapbox-developer-group/Mapbox-Tech-Q-A#40]
mapbox gl  对栅格base64加密的瓦片  如何去解密  后端返回的是一个base64加密的图片  mapbox在加载的时候  如何能解密返回png图片  我通过transformRequest 可以拦截到 tile请求   mapbox有什么机制可以解密操作吗

**Comment by canglaoshidaidui** [comment]
网页里有对 response的拦截么？ andorid里是有的呢，你重点看看这块吧。好像也有transformResponse这个吧！拦截服务返回的base64加密的图片，解密成byte[] 后再重新构建响应体应该就行了。 android端我是这样的。

**Comment by SCLGIS** [comment]
我已经在transformResponse里面拦截了 解密成byte[] 后再重新构建响应&nbsp; 具体怎么做&nbsp; 可以指导下嘛&nbsp; 感谢



---原始邮件---
发件人: "canglaoshidaidui"<notifications@github.com&gt;
发送时间: 2019年12月30日(周一) 晚上6:29
收件人: "mapbox-developer-group/Mapbox-Tech-Q-A"<Mapbox-Tech-Q-A@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"SCLGIS"<1648753530@qq.com&gt;;
主题: Re: [mapbox-developer-group/Mapbox-Tech-Q-A]  mapbox gl  对栅格base64加密的瓦片  如何去解密 (#40)



网页里有对 response的拦截么？ andorid里是有的呢，你重点看看这块吧。好像也有transformResponse这个吧！拦截服务返回的base64加密的图片，解密成byte[] 后再重新构建响应体应该就行了。 android端我是这样的。

**Comment by canglaoshidaidui** [comment]
![9GOAM95A$N6YWD_V7L6QO39](https://user-images.githubusercontent.com/9794418/71578804-a123e780-2b34-11ea-8722-9c41f98f6ed7.png)
![86F%WCCJD39`_{U%L~(20YT](https://user-images.githubusercontent.com/9794418/71578834-b862d500-2b34-11ea-9b8b-1ca843d4fe22.png)
大概有这几个参数，但是毕竟不是js的，得靠你自己了。。

**Comment by SCLGIS** [comment]
好的&nbsp; 我研究下&nbsp; 非常感谢了



---原始邮件---
发件人: "canglaoshidaidui"<notifications@github.com&gt;
发送时间: 2019年12月30日(周一) 晚上6:47
收件人: "mapbox-developer-group/Mapbox-Tech-Q-A"<Mapbox-Tech-Q-A@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"SCLGIS"<1648753530@qq.com&gt;;
主题: Re: [mapbox-developer-group/Mapbox-Tech-Q-A]  mapbox gl  对栅格base64加密的瓦片  如何去解密 (#40)




 
 大概有这几个参数，但是毕竟不是js的，得靠你自己了。。
