### ISSUE TITLE
技术小白请教，如何在mapbox底图上添加栅格数据

### ISSUE THREAD

**Issue by UncoDong** [mapbox-developer-group/Mapbox-Tech-Q-A#59]
## 我遇到的问题
作为一个大三前端知识的小白，我遇到了一个Web页面发布的问题。我现在需要将一个tif数据，以mapbox为底图，发布成html的页面。我已经在geoserver上将tif进行了切片，但我不知道在html中应该用什么url链接来访问到我的图象。我也网上找了很多例子，但都讲的是矢量切片数据的部署，几乎没有tif切片数据的。官方文档我也看了，可能因为不知道如何使用，也没有找到解决问题的方案...如果能够得到指点，或者让我知道我应该怎么去搜索我的问题，我将感激不尽。

## 我遇到的问题截图

![图片](https://user-images.githubusercontent.com/37969816/73586400-63c1c980-44e7-11ea-8d74-3bdfe853cf35.png)
我按照网上部署shp切片的方法，在geoserver的主页面中，右侧打开了TMS的1.0.0
![图片](https://user-images.githubusercontent.com/37969816/73586384-3ecd5680-44e7-11ea-9b74-e566ab867958.png)
找到了我在geoserver上进行发布的广东省的数据，但也不知道这是否就是正确的url...
![图片](https://user-images.githubusercontent.com/37969816/73586423-d8950380-44e7-11ea-8f29-f22044c7c2ed.png)
这是我在网上找到的html代码，似乎只需要替换横线这部分的内容就可以发布，但我怎么尝试也没能让广东省的图象显示在地图上。

我也在腾讯云买了一台服务器，如果需要的话我可以把这些数据发布在服务器上，可以访问并登录我服务器的geoserver来浏览数据。

## 该问题的类别

应该是Web，或者数据可视化方向的问题。

**Comment by canglaoshidaidui** [comment]
http://mt1.google.cn/vt/lyrs=s@113&hl=nl&x={x}&y={y}&z={z}&s=
这是google的栅格服务地址，自己部署的服务，感觉链接里需要提供 x,y,z这三个请求参数

**Comment by UncoDong** [comment]
@canglaoshidaidui 非常感谢~但我还有个问题是我看不懂这个地址的格式是什么...请问您知道这个地址是什么格式的吗？

**Comment by canglaoshidaidui** [comment]
mapbox发出数据请求时候会把链接里{x} {y} {z} 替换成 行列号和显示级别。比如：
http://mt1.google.cn/vt/lyrs=s@113&hl=nl&x=1&y=1&z=1&s=  你可以在浏览器里试一下就是一张图片了。 地图容器会根据 当前所在位置和显示级别  不停的去把瓦片请求回来。

**Comment by UncoDong** [comment]
@canglaoshidaidui 我确实通过修改参数也能访问到不同的瓦片了，但是像这段urlhttp://mt1.google.cn/vt/lyrs=s@113我不能理解是怎么定的，我确实是前端方面的小白...如果您能不厌其烦给我一些提示的话，非常感谢

**Comment by canglaoshidaidui** [comment]
你图片现在我刷不出来了，网上找的参考  https://www.jianshu.com/p/55f4f09c185a

http://localhost:8082/geoserver/gwc/service/tms/1.0.0/WMSTestMap%3AArestricted@ESPG%3A900913@pbf/{z}/{x}/{y}.pbf

http://localhost:8082/geoserver/gwc/service/tms/1.0.0/WMSTestMap%3AArestricted@ESPG%3A900913@pbf/{z}/{x}/{y}
这两个都试试。

**Comment by UncoDong** [comment]
呜呜，这个我之前也搜到过，不过格式是像shp文件这样的矢量切片，不是栅格图片的切片，不过还是谢谢您帮忙搜寻啦

**Comment by xietianyiii** [comment]
请问您成功添加栅格数据了嘛，我也遇到了相同的问题，如何您能不厌其烦的帮帮我，非常感谢

**Comment by UncoDong** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    没有成功，并且没有后续尝试了，不好意思没有帮上忙
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                1758322248
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
 
    

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年07月12日 18:18
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            Anning ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [mapbox-developer-group/Mapbox-Tech-Q-A] 技术小白请教，如何在mapbox底图上添加栅格数据 (#59)
        
      
    
  
  
请问您成功添加栅格数据了嘛，我也遇到了相同的问题，如何您能不厌其烦的帮帮我，非常感谢

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by UncoDong** [comment]
> 请问您成功添加栅格数据了嘛，我也遇到了相同的问题，如何您能不厌其烦的帮帮我，非常感谢

 没有成功，并且没有后续尝试了，不好意思没有帮上忙
